language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

before_install:
  - sudo apt-get update
  - sudo apt-get install netcdf libnetcdf-dev nco

install:
  # Get miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.3" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Make Conda test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file=ci/requirements-${TRAVIS_PYTHON_VERSION}.txt
  - source activate test-environment
  - python setup.py install

# command to run tests
script:
  - python -c "from nco import Nco"
  - py.test
